apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kconmon
  name: kconmon-service-monitor
  namespace: kconmon
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: http-web
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: kconmon
      component: agent
